<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2GSVMEN" ignored="2" name="D:/IdeaProject/interfaceRestAssured(failed)" tests="3" failures="3" timestamp="02 十二月 2020 05:57:16 GMT" time="0.018" errors="0">
  <testcase name="TestAssert" time="0.004" classname="TestNg.TestAssert">
    <failure type="java.lang.AssertionError" message="expected [2] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [2]
	at TestNg.TestAssert.TestAssert(TestAssert.java:10)
	at suit.RunSuit.main(RunSuit.java:28)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestAssert -->
  <testcase name="TestAssertnew" time="0.004" classname="TestNg.TestAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	两者不相等 expected [13] but found [12]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	两者不相等 expected [13] but found [12]
	at TestNg.TestAssert.TestAssertnew(TestAssert.java:34)
	at suit.RunSuit.main(RunSuit.java:28)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- TestAssertnew -->
  <testcase name="TestAssertW" time="0.003" classname="TestNg.TestAssert">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestNg.TestAssert.TestAssertW(TestAssert.java:25)
	at suit.RunSuit.main(RunSuit.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TestAssertW -->
  <testcase name="TestAssertThree" time="0.0" classname="TestNg.TestAssert">
    <ignored/>
  </testcase> <!-- TestAssertThree -->
  <testcase name="TestAssertFour" time="0.0" classname="TestNg.TestAssert">
    <ignored/>
  </testcase> <!-- TestAssertFour -->
</testsuite> <!-- D:/IdeaProject/interfaceRestAssured(failed) -->
